#ifndef SPA_UTILS_ERR_H_
#define SPA_UTILS_ERR_H_

#define SPA_UTILS_EBADINPUT 1
#define SPA_UTILS_ECANTALLOC 2
#define SPA_UTILS_EFOPEN 3
#define SPA_UTILS_EFSCANF 4
#define SPA_UTILS_EMATRICESINCOMP 5

#endif
